version: '3.8'

services:
  # Next.js Development Server
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      # DATABASE_URL should be set via .env file or environment variables
      # - DATABASE_URL=your_supabase_database_url
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - uploads_dev_data:/app/public/uploads
    restart: unless-stopped

volumes:
  uploads_dev_data:
